spring:
  jpa:
    show-sql: true
    open-in-view: false
  flyway:
    locations: classpath:db.migration
#    enabled: true
#    validate-on-migrate: true
#    baseline-on-migrate: true
  mvc:
    problem-details:
      enabled: true
    pathmatch:
      matching-strategy: ant_path_matcher
  kafka:
    consumer:
      auto-offset-reset: earliest
    listener:
      ack-mode: record
  application:
    name: testtask

kafka:
  topics:
    good: good
delays:
  order-event:
    send: 60000

logging:
  level:
    org.springframework:
      transaction: DEBUG